### ISSUE TITLE
EPIC: 8 - Contributor Consent and permissions management

### ISSUE THREAD

**Issue by benedictvscriticus** [hypercerts-org/hypercerts-org#26]
- [ ] As a hypercerts owner, I want to be able to signal my consent for including my hypercert on a hyperboard
- [ ] As a hyperboard owner, I want to permission access to the registry database of my hyperboards.
- [x] hypercerts-org/hypercerts#1083
- [ ] As a hyperboard owner, I want to create hypercert buleprints for contributors who do not yet have a wallet.
